### ISSUE TITLE
Je vůbec nutné používat odřádkování?

### ISSUE THREAD

**Issue by pavelhamrik** [tkohout/OSTRAJava#2]
Vzhledem k dovedně zvolenému oddělovači řádků — je nutné, aby kód používal tolik odřádkovávání? Snad by každý program měl být vždy one-liner, což je zároveň blízké způsobu ostravské mluvy.

**Comment by tkohout** [comment]
Odradkovani potreba neni. Kazdopadne odhaduji ze by to znacne zhorsilo citelnost kodu. Muze se jednoduse stat ze programator zapomene `pyco` a hledat pak chybu na jedne radce je problem. Navzdory sirokemu rozsireni jazyka jsme ale zatim zadne Coding Standards nevydali takze volbu nechavame na OSTRAJava programatorech.
