### ISSUE TITLE
Feature Request: Možnost importu java knihoven

### ISSUE THREAD

**Issue by kamenitxan** [tkohout/OSTRAJava#3]
Aktuálně není možné zkompilovat program používající java třídy. 

banik pyco

import java.util.Date pyco

tryda Ostrava{
    rynek(){
        toz Date d = new Date() pyco
        Konzola.pravit(d.getTime().naDryst()) pyco
    
    }

}

fajront pyco

**Comment by tkohout** [comment]
Je potreba se nad OSTRAJavou zamyslet jako nad uplne jinym jazykem ne jako na rozsirenim nad Javou. Hlavnim cilem jazyka je aby ho mohl pouzit i nevyskoleny hornik, takze nejake Date, import, util atd. nema v jazyce co delat. Resenim by bylo pridat podporu pro Date pres nativni funkce podobne jako je napriklad udelany [BufferedReader](https://github.com/tkohout/OSTRAJava/blob/master/src/main/java/cz/cvut/fit/ostrajava/Interpreter/Natives/IO/File/ReadLine.java) aneb [Citac](https://github.com/tkohout/OSTRAJava/blob/master/ostrajava_lib/src/Citac.cyp). Pull requesty jsou vitany.
