### ISSUE TITLE
Tabulator za kajtez generuje chybu prekladu

### ISSUE THREAD

**Issue by kkozlik** [tkohout/OSTRAJava#5]
Zda se ze u OSTRAjavy obecne nezalezi na tom zda je pouzita mezera nebo tabulator. Ale pri pouziti tabulatoru za ```kajtez``` dochazi k chybe prekladu.

Testovaci kod:
```
	cyslo chacharNaCyslo(chachar nejakyChachar){
		kaj (nejakyChachar == 'A')    { davaj 1 pyco } 
		kajtez (nejakyChachar == 'B') { davaj 2 pyco }
		kajtez (nejakyChachar == 'C') { davaj 3 pyco }
		kajtez (nejakyChachar == 'D') { davaj 4 pyco }
		kajtez (nejakyChachar == 'E') { davaj 5 pyco }
		kajtez (nejakyChachar == 'F') { davaj 6 pyco }
		boinak {
			Konzola.pravit("Fcil sme v pyci") pyco
			davaj 0 pyco
		}
	}
```

Pokud je za ```kajtez``` pouzita pouze mezera, preklad probehne bez problemu. Pokud pouziju tabulator dostanu pri prekladu nasledujici chybu:

> parse error in file Ostrava.cyp: Encountered " "kajtez" "kajtez "" at line 20, column 17.
> Was expecting one of:
>     "toz" ...
>     "forant" ...
>     "joch" ...
>     "chuj" ...
>     "fajne" ...
>     "nyt" ...
>     "zrob" ...
>     "kaj" ...
>     "boinak" ...
>     "rubat" ...
>     "zdybat" ...
>     "dlabat" ...
>     "davaj" ...
>     "dechrobok" ...
>     <INTEGER_LITERAL> ...
>     <FLOATING_POINT_LITERAL> ...
>     <CHARACTER_LITERAL> ...
>     <STRING_LITERAL> ...
>     "(" ...
>     "}" ...
>     <IDENTIFIER> ...
>     
> Exception in thread "main" cz.cvut.fit.ostrajava.Parser.ParseException: Encountered " "kajtez" "kajtez "" at line 20, column 17.
> Was expecting one of:
>     "toz" ...
>     "forant" ...
>     "joch" ...
>     "chuj" ...
>     "fajne" ...
>     "nyt" ...
>     "zrob" ...
>     "kaj" ...
>     "boinak" ...
>     "rubat" ...
>     "zdybat" ...
>     "dlabat" ...
>     "davaj" ...
>     "dechrobok" ...
>     <INTEGER_LITERAL> ...
>     <FLOATING_POINT_LITERAL> ...
>     <CHARACTER_LITERAL> ...
>     <STRING_LITERAL> ...
>     "(" ...
>     "}" ...
>     <IDENTIFIER> ...
>     
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.generateParseException(OSTRAJavaParser.java:4393)
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.jj_consume_token(OSTRAJavaParser.java:4271)
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.Block(OSTRAJavaParser.java:2502)
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.MethodDeclaration(OSTRAJavaParser.java:480)
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.ClassBodyDeclaration(OSTRAJavaParser.java:156)
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.ClassDeclaration(OSTRAJavaParser.java:118)
>         at cz.cvut.fit.ostrajava.Parser.OSTRAJavaParser.CompilationUnit(OSTRAJavaParser.java:38)
>         at cz.cvut.fit.ostrajava.Compile.parse(Compile.java:183)
>         at cz.cvut.fit.ostrajava.Compile.exec(Compile.java:69)
>         at cz.cvut.fit.ostrajava.Main.main(Main.java:28)
>

**Comment by tkohout** [comment]
Diky za nahlaseni bugu, opraveno v 94c15f89421ccc8ebfcb69a1ef8f1f8b1c9c899c
