### ISSUE TITLE
Feature request: distribuce zkompilovane ostrajavy

### ISSUE THREAD

**Issue by kkozlik** [tkohout/OSTRAJava#7]
Dobry den,
nezvazujete distribuovat krome zdrojovych kodu take zkompilovanou ostrajavu? Patrne by stacil nejaky zip/tgz ktery by obsahoval prelozeny jar a ostrajava_lib.

Nasim uzivatelum by to velmi zjednodusilo pouziti ostrajavy.

**Comment by tkohout** [comment]
Diky, super by bylo dostat to jeste do nejakych balickovacich systemu (jako treba homebrew) ale moc se mi do toho zatim nechce.
