### ISSUE TITLE
[Exception]

### ISSUE THREAD

**Issue by TekuSP** [tkohout/OSTRAJava#9]
Compile vždy na dá na první řádek "????"
Run pak vyhodí exception že "????" není  číslo.

Pochopil jsem správně spouštění? Compile a pak Run?

**Comment by tkohout** [comment]
Ano, program je napřed potřeba zkompilovat do OSTRAJava bytecodu (soubory .tryda).
Ten vzdy zacina sekvenci hexa znaku:

```
0xCA
0xFE
0xBA
0xBA
```
Coz zrejme nedokaze vas textovy prohlizec identifikovat a nahradi je za ????

Duvodu proc vam nejde spustit kod muze byt vice, poslete cely kod vyjimky, kompilovany kod, bytecode, verzi ostrajavy a systemu na kterem OSTRAJavu spoustite.

**Comment by tkohout** [comment]
Uzaviram kvuli neaktivite
